# =============================================================================
# Kubernetes Service Account with GKE Workload Identity Annotation
# =============================================================================
#
# This KSA is annotated with a GCP service account email, which tells the
# GKE metadata server to issue GCP OAuth2 tokens for the mapped GSA when
# pods using this KSA request credentials via the metadata server.
#
# HOW IT WORKS:
# 1. Pod mounts this KSA via spec.serviceAccountName
# 2. Pod calls metadata server: GET http://169.254.169.254/...
# 3. GKE metadata proxy intercepts the request
# 4. Proxy reads the KSA annotation to find the target GSA
# 5. Proxy requests a short-lived OAuth2 token from IAM Credentials API
# 6. IAM validates the KSA->GSA binding (roles/iam.workloadIdentityUser)
# 7. If valid, IAM returns a 1-hour access token
# 8. Proxy returns the token to the pod
# 9. Pod uses the token for GCP API calls
#
# PREREQUISITES:
# - GKE cluster has Workload Identity enabled
# - terraform-gke-wi.tf has been applied (creates GSA, IAM binding)
# - The annotation email matches exactly what is in the IAM binding
#
# =============================================================================

---
# Namespace for security tooling
apiVersion: v1
kind: Namespace
metadata:
  name: security-tools
  labels:
    name: security-tools
    app.kubernetes.io/managed-by: kubectl
    # Pod Security Standards - enforce restricted profile
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest

---
# Trivy Operator Service Account
# Maps to: trivy-operator-wi-prod@<PROJECT_ID>.iam.gserviceaccount.com
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: security-tools
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/component: vulnerability-scanner
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: devsecops-security
  annotations:
    # CRITICAL: This annotation links the KSA to the GSA.
    # The email MUST match the GSA created in terraform-gke-wi.tf.
    # If this annotation is wrong, the pod will get "permission denied" errors.
    iam.gke.io/gcp-service-account: "trivy-operator-wi-prod@PROJECT_ID.iam.gserviceaccount.com"
    # Description for auditability
    description: "Trivy Operator - scans container images and writes results to BigQuery"
automountServiceAccountToken: false

---
# Falco Service Account
# Maps to: falco-wi-prod@<PROJECT_ID>.iam.gserviceaccount.com
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: security-tools
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/component: runtime-security
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: devsecops-security
  annotations:
    iam.gke.io/gcp-service-account: "falco-wi-prod@PROJECT_ID.iam.gserviceaccount.com"
    description: "Falco - runtime security monitoring, publishes events to Pub/Sub and BigQuery"
automountServiceAccountToken: false

---
# Suricata Service Account
# Maps to: suricata-wi-prod@<PROJECT_ID>.iam.gserviceaccount.com
apiVersion: v1
kind: ServiceAccount
metadata:
  name: suricata
  namespace: security-tools
  labels:
    app.kubernetes.io/name: suricata
    app.kubernetes.io/component: network-ids
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: devsecops-security
  annotations:
    iam.gke.io/gcp-service-account: "suricata-wi-prod@PROJECT_ID.iam.gserviceaccount.com"
    description: "Suricata IDS - network intrusion detection, writes alerts to BigQuery"
automountServiceAccountToken: false

---
# BigQuery Exporter Service Account (default namespace)
# Maps to: bq-exporter-wi-prod@<PROJECT_ID>.iam.gserviceaccount.com
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bq-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: bq-exporter
    app.kubernetes.io/component: data-pipeline
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: devsecops-security
  annotations:
    iam.gke.io/gcp-service-account: "bq-exporter-wi-prod@PROJECT_ID.iam.gserviceaccount.com"
    description: "BigQuery exporter - aggregates and processes security findings"
automountServiceAccountToken: false

---
# Log Shipper Service Account (default namespace)
# Maps to: log-shipper-wi-prod@<PROJECT_ID>.iam.gserviceaccount.com
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-shipper
  namespace: default
  labels:
    app.kubernetes.io/name: log-shipper
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: devsecops-security
  annotations:
    iam.gke.io/gcp-service-account: "log-shipper-wi-prod@PROJECT_ID.iam.gserviceaccount.com"
    description: "Log shipper - exports pod logs to Cloud Storage for long-term retention"
automountServiceAccountToken: false
